# Generated by Django 4.0.6 on 2023-09-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('meal_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meal_name', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
            },
        ),
    ]
