# Generated by Django 4.0.6 on 2023-09-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_remove_basketmodel_user_id_basketmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketmodel',
            name='meal_id',
        ),
    ]
