# Generated by Django 4.0.6 on 2023-09-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_remove_basketmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='user',
            field=models.CharField(default='behruz', max_length=50),
            preserve_default=False,
        ),
    ]
